from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = ("en", "zh")
LANGUAGE_NAMES = {"en": "English", "zh": "中文"}


TRANSLATIONS: dict[str, dict[str, str]] = {
    "en": {
        "app.title": "Assignments",
        "brand.subtitle": "Student workspace",
        "nav.section": "WORKSPACE",
        "nav.all": "All Assignments",
        "nav.today": "Today",
        "nav.week": "This Week",
        "nav.completed": "Completed",
        "nav.sources": "Sources",
        "nav.settings": "Settings",
        "view.all.title": "Assignments",
        "view.all.description": "Everything on your schedule, beautifully organized.",
        "view.today.title": "Today",
        "view.today.description": "A focused view of what needs your attention today.",
        "view.week.title": "This Week",
        "view.week.description": "Plan the next seven days with room to breathe.",
        "view.completed.title": "Completed",
        "view.completed.description": "A calm record of everything you have finished.",
        "view.sources.title": "Sources",
        "view.sources.description": "Assignments collected from your connected and imported sources.",
        "view.settings.title": "Settings",
        "view.settings.description": "Make the workspace feel right for you.",
        "greeting.morning": "Good morning",
        "greeting.afternoon": "Good afternoon",
        "greeting.evening": "Good evening",
        "connection.connecting": "Connecting…",
        "connection.online": "Local service online",
        "connection.offline": "Service offline",
        "action.import_html": "↗  Import HTML",
        "action.new_assignment": "+  New Assignment",
        "action.clear_filters": "Clear filters",
        "action.edit": "Edit",
        "action.done": "✓  Done",
        "metric.open": "Open",
        "metric.due_today": "Due today",
        "metric.this_week": "This week",
        "metric.completed": "Completed",
        "search.placeholder": "Search assignments, courses, or sources",
        "filter.all_statuses": "All statuses",
        "filter.not_started": "Not started",
        "filter.in_progress": "In progress",
        "filter.completed": "Completed",
        "filter.all_courses": "All courses",
        "parser.auto": "Auto",
        "parser.ai": "AI",
        "parser.rule": "Rule-based",
        "list.count.one": "{count} assignment",
        "list.count.other": "{count} assignments",
        "list.sort": "Soonest due first",
        "privacy": "Local-first · Your data stays on this device",
        "settings.language.title": "Language",
        "settings.language.description": "Choose the language used throughout the workspace.",
        "settings.appearance.title": "Appearance",
        "settings.appearance.description": "Follow your system or choose a dedicated light or dark workspace.",
        "settings.appearance.system": "System",
        "settings.appearance.light": "Light",
        "settings.appearance.dark": "Dark",
        "settings.motion.title": "Motion",
        "settings.motion.description": "Use gentle transitions when cards appear, respond, and leave the list.",
        "settings.motion.toggle": "Smooth interface animations",
        "settings.data.title": "Data & connection",
        "settings.data.description": "Assignment records remain in the existing local SQLite database.",
        "settings.data.endpoint": "Local API   {url}",
        "status.syncing": "Syncing your schedule…",
        "status.unavailable": "Local service is unavailable.",
        "status.updated": "Updated just now · {count} assignments in your library",
        "status.removed": "Removed \"{title}\"",
        "empty.first.title": "A clear slate",
        "empty.first.body": "Create your first assignment and give every deadline a calm place to live.",
        "empty.filtered.title": "Nothing here right now",
        "empty.filtered.body": "Try another view or clear the filters to see more of your schedule.",
        "dialog.load_error": "Cannot load assignments",
        "dialog.select_html": "Select assignment HTML file",
        "dialog.html_files": "HTML files",
        "dialog.all_files": "All files",
        "dialog.default_course": "Default course name for imported assignments:",
        "dialog.html_import": "HTML Import",
        "dialog.import_error": "Cannot import HTML",
        "dialog.import_dependency": "HTML import needs beautifulsoup4. Install requirements and try again.\n\n{error}",
        "dialog.parse_error": "Cannot parse HTML",
        "dialog.no_assignments": "No assignments found",
        "dialog.no_assignments.body": "No assignments found. You can try another HTML file or paste text manually later.",
        "dialog.delete": "Delete assignment",
        "dialog.delete_confirm": "Delete \"{title}\"?",
        "dialog.delete_error": "Cannot delete assignment",
        "dialog.update_error": "Cannot update assignment",
        "fallback.assignment": "this assignment",
        "card.no_course": "NO COURSE",
        "card.untitled": "Untitled assignment",
        "card.no_source": "None",
        "due.none": "No due date",
        "due.today": "Due today",
        "due.tomorrow": "Due tomorrow",
        "due.in_days": "Due in {days} days",
        "due.overdue_one": "Overdue by 1 day",
        "due.overdue_days": "Overdue by {days} days",
        "due.completed": "Completed  ·  {date} at {time}",
        "due.detail": "{relative}  ·  {date} at {time}",
        "status.not_started": "Not started",
        "status.in_progress": "In progress",
        "status.completed": "Completed",
        "status.todo": "To do",
        "status.done": "Done",
        "status.ignored": "Ignored",
        "form.window.edit": "Edit Assignment",
        "form.window.new": "New Assignment",
        "form.heading.edit": "Edit assignment",
        "form.heading.new": "Create an assignment",
        "form.subtitle": "Keep the important details together and easy to scan.",
        "form.section.details": "ASSIGNMENT DETAILS",
        "form.course": "Course",
        "form.course.placeholder": "e.g. CSE 122",
        "form.title": "Title",
        "form.title.placeholder": "What needs to be done?",
        "form.due_date": "Due date",
        "form.time": "Time",
        "form.description": "Description",
        "form.description.placeholder": "Add notes, requirements, or a helpful next step…",
        "form.section.source": "SOURCE & PROGRESS",
        "form.source": "Source",
        "form.source.placeholder": "Canvas, course site, or manual",
        "form.source_url": "Source URL",
        "form.status": "Status",
        "form.cancel": "Cancel",
        "form.save": "Save Assignment",
        "form.save_error": "Cannot save assignment",
        "form.error.course": "Course name is required.",
        "form.error.title": "Assignment title is required.",
        "form.error.date": "Due date must be YYYY-MM-DD and due time must be HH:MM.",
        "import.window": "Review Imported Assignments",
        "import.heading": "Review imported assignments",
        "import.ready": "{count} possible assignments are ready for review.",
        "import.parser": "Parser used: {parser}",
        "import.unknown": "unknown",
        "import.fallback": "AI parser was not available. Rule-based parser was used instead.",
        "import.cancel": "Cancel",
        "import.all": "Import All",
        "import.course": "Course name",
        "import.title": "Title",
        "import.due_date": "Due date (YYYY-MM-DD)",
        "import.due_time": "Due time (HH:MM)",
        "import.source_name": "Source name",
        "import.source_file": "Source file",
        "import.confidence": "Confidence: {confidence}",
        "import.medium": "medium",
        "import.warnings": "Warnings: {warnings}",
        "import.description": "Description",
        "import.one": "Import",
        "import.ignore": "Ignore",
        "import.error": "Cannot import assignment",
        "import.some_error": "Some assignments were not imported",
        "import.complete": "Import complete",
        "import.completed_count": "Imported {count} assignments.",
        "import.error.course": "Course name is required before importing.",
        "import.error.title": "Title is required before importing.",
        "import.error.date": "Due date must be blank or use YYYY-MM-DD and optional HH:MM.",
        "import.error.time": "Due time cannot be imported without a due date.",
        "import.remaining": "{count} assignments left to review.",
    },
    "zh": {
        "app.title": "作业管理",
        "brand.subtitle": "学生工作台",
        "nav.section": "工作区",
        "nav.all": "全部作业",
        "nav.today": "今天",
        "nav.week": "本周",
        "nav.completed": "已完成",
        "nav.sources": "来源",
        "nav.settings": "设置",
        "view.all.title": "作业",
        "view.all.description": "清晰整理日程中的每一项作业。",
        "view.today.title": "今天",
        "view.today.description": "专注查看今天需要处理的事项。",
        "view.week.title": "本周",
        "view.week.description": "从容安排接下来七天的任务。",
        "view.completed.title": "已完成",
        "view.completed.description": "查看所有已经完成的作业。",
        "view.sources.title": "来源",
        "view.sources.description": "查看从已连接或已导入来源收集的作业。",
        "view.settings.title": "设置",
        "view.settings.description": "按你的习惯调整工作区。",
        "greeting.morning": "早上好",
        "greeting.afternoon": "下午好",
        "greeting.evening": "晚上好",
        "connection.connecting": "正在连接…",
        "connection.online": "本地服务在线",
        "connection.offline": "服务离线",
        "action.import_html": "↗  导入 HTML",
        "action.new_assignment": "+  新建作业",
        "action.clear_filters": "清除筛选",
        "action.edit": "编辑",
        "action.done": "✓  完成",
        "metric.open": "待完成",
        "metric.due_today": "今天截止",
        "metric.this_week": "本周截止",
        "metric.completed": "已完成",
        "search.placeholder": "搜索作业、课程或来源",
        "filter.all_statuses": "全部状态",
        "filter.not_started": "未开始",
        "filter.in_progress": "进行中",
        "filter.completed": "已完成",
        "filter.all_courses": "全部课程",
        "parser.auto": "自动",
        "parser.ai": "AI",
        "parser.rule": "规则解析",
        "list.count.one": "{count} 项作业",
        "list.count.other": "{count} 项作业",
        "list.sort": "按截止时间排序",
        "privacy": "本地优先 · 数据保留在此设备上",
        "settings.language.title": "语言",
        "settings.language.description": "选择整个工作区使用的语言。",
        "settings.appearance.title": "外观",
        "settings.appearance.description": "跟随系统，或固定使用浅色或深色模式。",
        "settings.appearance.system": "跟随系统",
        "settings.appearance.light": "浅色",
        "settings.appearance.dark": "深色",
        "settings.motion.title": "动效",
        "settings.motion.description": "在卡片出现、响应和移出列表时使用柔和过渡。",
        "settings.motion.toggle": "流畅界面动画",
        "settings.data.title": "数据与连接",
        "settings.data.description": "作业记录仍保存在现有的本地 SQLite 数据库中。",
        "settings.data.endpoint": "本地 API   {url}",
        "status.syncing": "正在同步作业日程…",
        "status.unavailable": "本地服务不可用。",
        "status.updated": "刚刚更新 · 作业库中共有 {count} 项",
        "status.removed": "已删除“{title}”",
        "empty.first.title": "从容开始",
        "empty.first.body": "创建第一项作业，让每个截止日期都有清晰的位置。",
        "empty.filtered.title": "这里暂时没有内容",
        "empty.filtered.body": "尝试其他视图，或清除筛选以查看更多日程。",
        "dialog.load_error": "无法加载作业",
        "dialog.select_html": "选择作业 HTML 文件",
        "dialog.html_files": "HTML 文件",
        "dialog.all_files": "所有文件",
        "dialog.default_course": "导入作业的默认课程名称：",
        "dialog.html_import": "导入 HTML",
        "dialog.import_error": "无法导入 HTML",
        "dialog.import_dependency": "HTML 导入需要 beautifulsoup4。请安装依赖后重试。\n\n{error}",
        "dialog.parse_error": "无法解析 HTML",
        "dialog.no_assignments": "未找到作业",
        "dialog.no_assignments.body": "未找到作业。你可以尝试其他 HTML 文件，或稍后手动粘贴文本。",
        "dialog.delete": "删除作业",
        "dialog.delete_confirm": "要删除“{title}”吗？",
        "dialog.delete_error": "无法删除作业",
        "dialog.update_error": "无法更新作业",
        "fallback.assignment": "这项作业",
        "card.no_course": "无课程",
        "card.untitled": "未命名作业",
        "card.no_source": "无",
        "due.none": "无截止日期",
        "due.today": "今天截止",
        "due.tomorrow": "明天截止",
        "due.in_days": "{days} 天后截止",
        "due.overdue_one": "已逾期 1 天",
        "due.overdue_days": "已逾期 {days} 天",
        "due.completed": "已完成  ·  {date} {time}",
        "due.detail": "{relative}  ·  {date} {time}",
        "status.not_started": "未开始",
        "status.in_progress": "进行中",
        "status.completed": "已完成",
        "status.todo": "待办",
        "status.done": "完成",
        "status.ignored": "已忽略",
        "form.window.edit": "编辑作业",
        "form.window.new": "新建作业",
        "form.heading.edit": "编辑作业",
        "form.heading.new": "创建作业",
        "form.subtitle": "集中填写重要信息，方便快速查看。",
        "form.section.details": "作业详情",
        "form.course": "课程",
        "form.course.placeholder": "例如：高等数学",
        "form.title": "标题",
        "form.title.placeholder": "需要完成什么？",
        "form.due_date": "截止日期",
        "form.time": "时间",
        "form.description": "说明",
        "form.description.placeholder": "添加备注、要求或下一步计划…",
        "form.section.source": "来源与进度",
        "form.source": "来源",
        "form.source.placeholder": "Canvas、课程网站或手动添加",
        "form.source_url": "来源网址",
        "form.status": "状态",
        "form.cancel": "取消",
        "form.save": "保存作业",
        "form.save_error": "无法保存作业",
        "form.error.course": "课程名称不能为空。",
        "form.error.title": "作业标题不能为空。",
        "form.error.date": "截止日期须为 YYYY-MM-DD，时间须为 HH:MM。",
        "import.window": "检查导入的作业",
        "import.heading": "检查导入的作业",
        "import.ready": "有 {count} 项可能的作业待检查。",
        "import.parser": "使用的解析器：{parser}",
        "import.unknown": "未知",
        "import.fallback": "AI 解析器不可用，已改用规则解析器。",
        "import.cancel": "取消",
        "import.all": "全部导入",
        "import.course": "课程名称",
        "import.title": "标题",
        "import.due_date": "截止日期 (YYYY-MM-DD)",
        "import.due_time": "截止时间 (HH:MM)",
        "import.source_name": "来源名称",
        "import.source_file": "来源文件",
        "import.confidence": "可信度：{confidence}",
        "import.medium": "中",
        "import.warnings": "警告：{warnings}",
        "import.description": "说明",
        "import.one": "导入",
        "import.ignore": "忽略",
        "import.error": "无法导入作业",
        "import.some_error": "部分作业未能导入",
        "import.complete": "导入完成",
        "import.completed_count": "已导入 {count} 项作业。",
        "import.error.course": "导入前必须填写课程名称。",
        "import.error.title": "导入前必须填写标题。",
        "import.error.date": "截止日期可留空，或使用 YYYY-MM-DD 和可选的 HH:MM。",
        "import.error.time": "填写截止时间前必须先填写截止日期。",
        "import.remaining": "还有 {count} 项作业待检查。",
    },
}


def translate(language: str, key: str, **values: Any) -> str:
    selected = language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE
    template = TRANSLATIONS.get(selected, {}).get(key, TRANSLATIONS[DEFAULT_LANGUAGE].get(key, key))
    return template.format(**values) if values else template


def preferences_path() -> Path:
    override = os.environ.get("ASSIGNMENT_APP_PREFERENCES")
    if override:
        return Path(override).expanduser()
    return Path.home() / ".assignment-app" / "preferences.json"


def load_language() -> str:
    try:
        data = json.loads(preferences_path().read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return DEFAULT_LANGUAGE
    language = data.get("language") if isinstance(data, dict) else None
    return language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE


def save_language(language: str) -> None:
    if language not in SUPPORTED_LANGUAGES:
        raise ValueError(f"Unsupported language: {language}")
    path = preferences_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    data: dict[str, Any] = {}
    try:
        existing = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(existing, dict):
            data.update(existing)
    except (OSError, ValueError, TypeError):
        pass
    data["language"] = language
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
