<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AssignmentNative.Core.Tests</RootNamespace>
    <AssemblyName>AssignmentNative.Core.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssignmentNative.Core\AssignmentNative.Core.csproj" />
  </ItemGroup>
</Project>
